// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================



/* ***************** Module ************/
module UART_top(


//`ifdef ENABLE_CLOCK1
input   		MAX10_CLK1_50,
//`endif

/*
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,
*/

	input 		     [1:0]		KEY


//	output		     [9:0]		LEDR,


//	input 		     [9:0]		SW,

);


wire Rx_valid;
wire [7:0] rx_data;

wire iTx_DV; // data to transmitis valid. start transmitting
wire iRx_serial; // the serial stream
wire [7:0] i_Tx_Byte;
wire o_Tx_Active;
wire o_Tx_Serial;
wire o_Tx_Done;
reg reset;

always @(posedge MAX10_CLK1_50) begin
reset = ~KEY[0];
end

//always @(*) begin
assign iRx_serial=o_Tx_Serial;
//end


UART my_uart(MAX10_CLK1_50,KEY[0],iRx_serial,Rx_valid,rx_data,iTx_DV,i_Tx_Byte,o_Tx_Active,o_Tx_Serial,o_Tx_Done);
tx_activate tx_act(MAX10_CLK1_50,reset,iTx_DV,i_Tx_Byte);

endmodule
